### ISSUE TITLE
Add Manifest change check at the start of the Master Notebook

### ISSUE THREAD

**Issue by jrampono** [Insight-Services-APAC/APAC-Capability-DAI-DbtFabricSparkNb#30]
```[tasklist]
### Tasks
- [x] Add hash creation to metaextract noteb
- [x] Add metadata refresh and hash check to master notebook
- [ ] Test against multiple environments
```
